name: UnitTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, '**' ]
    
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3
    - name: Install xcpretty
      run: gem install xcpretty
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Run tests
      run: xcodebuild build-for-testing -project XKCDViewer/XKCDViewer.xcodeproj -scheme XKCDViewerTests -destination 'platform=iOS Simulator,name=iPhone 16' test-without-building | xcpretty && exit ${PIPESTATUS[0]}
